on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.charlesobinnafoundation.org
        username: lg_993847_92939_lweujs@lg.charlesobinnafoundation.org
        password: $$lg_948809247_92939_lweujs_227
        protocol: ftps
